services:
  vb.bookstore.api:
    image: vb.bookstore.api
    build:
      context: .
      dockerfile: VB.BookStore.Api/Dockerfile
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "TestPassword@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
volumes:
  sql_data:

